food = raw_input("Provide favorite food")
resturant  = raw_input("Provide favorite resturant")
resturant = raw_input("Provide favorite resturant")
artist = raw_input("Provide favorite song writer")
Book = raw_input("Provide favorite book")
madlib = raw_input("")